### ISSUE TITLE
Refactor API

### ISSUE THREAD

**Issue by SOSANA** [EQuimper/streamingAppRedux#54]
gonna do a pr to refactor so your api url so you don't have to replace it all over

**Comment by EQuimper** [comment]
You mean with the api_key ?

**Comment by SOSANA** [comment]
with api url, just forked and about to update...is there anything in config I should know prior? Have you done any tests against your api url to see if it passes? so in future it will fail test etc

**Comment by EQuimper** [comment]
nop nothing that was just for learning ;)

**Comment by SOSANA** [comment]
@EQuimper might setup a quick mock with mocha and chai if your cool with it, might run out of time with kids coming home soon lol

**Comment by EQuimper** [comment]
no problem go for ;)
